### ISSUE TITLE
No type

### ISSUE THREAD

**Issue by gtanime** [dynamiquel/Game-Bar-Browser#18]
im not sure if anyone else has this issue but when i go to type in the browser it wont let me type or paste anything, everything else like clicking works. when i reboot it works for a while then wit wont let me type again, i have tried reinstalling but have the same issue

**Comment by dynamiquel** [comment]
This is a known limitation of the **WebView API** that is used by the browser. Unfortunately, there is nothing that I can do about that. It's Microsoft's problem and they discontinued the API a long time ago.

The reasoning for this is because you have another app 'selected' in the background. (Basically, if your Taskbar is highlighting an app, then keyboard input in the browser will not work). When it comes to games, it tends to be hit or miss.
A simple fix is to simply press your Desktop before using the browser as this way, no app is selected.

**Comment by dynamiquel** [comment]
The only possible fix I can see is to use Microsoft's **WebView 2 API**. However, I don't believe this yet works with Xbox Game Bar.

**Comment by dynamiquel** [comment]
I will attempt to find out why the old version did not have this problem but the new one does.

**Comment by dynamiquel** [comment]
Issue fixed. Problem was due to the 5.3 Game Bar SDK update. The app has been rolledback to 5.1.
