### ISSUE TITLE
Twitch is not loading - sorry bug seems to be back. XD

### ISSUE THREAD

**Issue by Sinusflorian** [dynamiquel/Game-Bar-Browser#39]
The Gamebrowser don't load Twitch, i saw, that that was already some time ago fixed, but it don't work for me. XD Attaching Pictuce.  Sidenote: Youtube is working normally. 
![Screenshot (317)](https://user-images.githubusercontent.com/93134772/138696062-8597f2d4-b433-4d85-b0f6-475d418e162e.png)

**Comment by dynamiquel** [comment]
Hi. Sorry for misleading you. The bug is fixed in the unreleased (Chromium) branch.
I cannot yet release the new branch because there seems to be an issue on the Game Bar team's end of things.
_see here: https://github.com/dynamiquel/GameBarBrowser/issues/34#issuecomment-913000742_


It is not possible for me to fix Twitch and other demanding 'modern' websites until that issue is fixed since it is a fundamental flaw of the old WebView (old Microsoft Edge).

**Comment by Sinusflorian** [comment]
Ahh ok, no problem. But thanks for the Anwer. 👍👍
